services:
    mosquitto:
        container_name: mqtt-broker
        image: eclipse-mosquitto:2.0.20
        restart: always
        ports:
            - 1883:1883
        volumes:
            - ./docker/mosquitto/config:/mosquitto/config
            - ./docker/mosquitto/data:/mosquitto/data
            - ./docker/mosquitto/log:/mosquitto/log
        networks:
            - tonttutrack-network
    tonttutrack:
        container_name: tonttutrack-web
        image: tonttutrack-csharp-image
        ports:
            - 5001:8080
        depends_on:
            - postgresql
        networks:
            - tonttutrack-network
    postgresql:
        container_name: tonttutrack-database
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - tonttutrack-network
volumes:
    db-data:
        name: tonttutrack-db-volume
networks:
    tonttutrack-network:
        driver: bridge
        name: tonttutrack-network